[package]
name = "rs-utils"
version = "0.3.0"
authors = ["Shane Pearman <spearman@github.com>"]

[dependencies]
unwrap = "1.*"
lazy_static = "0.2.*"

[dev-dependencies]
tempdir = "0.3.*"
quickcheck = "0.4.*"
quickcheck_macros = "0.4.*"
