[package]
name = "rs-utils"
version = "0.0.11"
authors = ["Shane Pearman <spearman@github.com>"]
license = "Apache-2.0"

[dependencies]
lazy_static = "1.*"

[dev-dependencies]
quickcheck = "0.6.*"
quickcheck_macros = "0.6.*"
tempdir = "0.3.*"
unwrap = "1.*"
