[package]
name = "rs-utils"
version = "0.0.21"
authors = ["Shane Pearman <spearman@gitlab.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4.*"
stdext = "0.3.*"

[dev-dependencies]
env_logger = "0.10.*"
quickcheck = "1.*"
quickcheck_macros = "1.*"
tempfile = "3.*"
