[package]
name = "rs-utils"
version = "0.0.10"
authors = ["Shane Pearman <spearman@github.com>"]
license = "Apache-2.0"

[dependencies]
lazy_static = "1.*"

[dev-dependencies]
quickcheck = "0.4.*"
quickcheck_macros = "0.4.*"
tempdir = "0.3.*"
unwrap = "1.*"
