[package]
name = "rs-utils"
version = "0.0.14"
authors = ["Shane Pearman <spearman@github.com>"]
license = "Apache-2.0"

[dependencies]
generic-array = "0.13.*"
rand_core = "0.5.*"
rand_xorshift = "0.2.*"
typenum = "1.*"

[dev-dependencies]
quickcheck = "0.9.*"
quickcheck_macros = "0.8.*"
tempdir = "0.3.*"
unwrap = "1.*"
rand = "0.7.*"
