[package]
name = "rs-utils"
version = "0.0.9"
authors = ["Shane Pearman <spearman@github.com>"]
license = "Apache-2.0"

[dependencies]
lazy_static = "0.2.*"
num = "0.1.*"

[dev-dependencies]
quickcheck = "0.4.*"
quickcheck_macros = "0.4.*"
tempdir = "0.3.*"
macro-attr = "0.2.*"
enum_derive = "0.1.*"
unwrap = "1.*"
