[package]
name = "rs-utils"
version = "0.0.15"
authors = ["Shane Pearman <spearman@github.com>"]
license = "Apache-2.0"

[dependencies]
generic-array = "0.13.*"
typenum = "1.*"

[dev-dependencies]
quickcheck = "0.9.*"
quickcheck_macros = "0.8.*"
tempdir = "0.3.*"
unwrap = "1.*"
