[package]
name = "rs-utils"
version = "0.0.16"
authors = ["Shane Pearman <spearman@github.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
clap = "2.*"
generic-array = "0.13.*"
log = "0.4.*"
simplelog = "0.7.*"
typenum = "1.*"

[dev-dependencies]
quickcheck = "0.9.*"
quickcheck_macros = "0.8.*"
tempdir = "0.3.*"
unwrap = "1.*"
