[package]
name = "rs-utils"
version = "0.2.0"
authors = ["Shane Pearman <spearman@github.com>"]

[dependencies]

[dev-dependencies]
unwrap = "1.1.0"
tempdir = "0.3.5"
quickcheck = "0.4.1"
quickcheck_macros = "0.4.1"
