[package]
name = "rs-utils"
version = "0.0.18"
authors = ["Shane Pearman <spearman@github.com>"]
license = "Apache-2.0"
edition = "2021"

[features]
app = ["clap", "log", "simplelog"]

[dependencies]
generic-array = "0.14.*"
typenum = "1.*"
# optional
clap = { version = "3.*", optional = true }
log = { version = "0.4.*", optional = true }
simplelog = { version = "0.12.*", optional = true }

[dev-dependencies]
quickcheck = "1.*"
quickcheck_macros = "1.*"
rs-utils = { version = "*", path = "./.", features = ["app"] }
tempfile = "3.*"
unwrap = "1.*"
